//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroLabsFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Detalle = new HashSet<Detalle>();
        }
    
        public string codigoProducto { get; set; }
        public string nombreProducto { get; set; }
        public string tipoProducto { get; set; }
        public string descripcionProducto { get; set; }
        public System.DateTime fechaVencimiento { get; set; }
        public int cantCajas { get; set; }
        public int cantUnidades { get; set; }
        public int codigoProveedor { get; set; }
        public string nombreQuickbooks { get; set; }
        public Nullable<int> totalProducto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle> Detalle { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
