//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroLabsFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int idUsuario { get; set; }
        public string nombreUsuario { get; set; }
        public string apellido1 { get; set; }
        public string apellido2 { get; set; }
        public string correoUsuario { get; set; }
        public string password { get; set; }
        public int idRol { get; set; }
    
        public virtual Rol Rol { get; set; }
    }
}
